style"dialogs"{
bg[NORMAL]=@bg_color
bg[PRELIGHT]=@bg_color
bg[SELECTED]=@bg_color
bg[ACTIVE]=@bg_color
bg[INSENSITIVE]=@bg_color
fg[NORMAL]=@fg_color
fg[PRELIGHT]=@fg_color
fg[SELECTED]=@fg_color
fg[ACTIVE]=@fg_color
fg[INSENSITIVE]=@fg_color}
class"GtkAssistant"style"dialogs"
class"GtkAboutDialog"style"dialogs"
class"GtkColorSelectionDialog"style"dialogs"
class"GtkFileSelection"style"dialogs"
class"GtkFontSelectionDialog"style"dialogs"
class"GtkInputDialog"style"dialogs"
class"GtkMessageDialog"style"dialogs"
class"GtkPageSetupUnixDialog"style"dialogs"
class"GtkPrintUnixDialog"style"dialogs"
class"GtkRecentChooserDialog"style"dialogs"
class"GtkRecentChooserDialog"style"dialogs"
