style"groupbox"{
xthickness=1
ythickness=1
engine"pixmap"{
image{
function=SHADOW_GAP
shadow=IN
file="images/shadowgroupbox.png"
border={1,1,0,1}
stretch=TRUE
gap_start_file="images/shadowgroupboxgap.png"
gap_end_file="images/shadowgroupboxgap.png"}
image{
function=SHADOW_GAP
shadow=ETCHED_IN
file="images/shadowgroupbox.png"
border={1,1,0,1}
stretch=TRUE
gap_start_file="images/shadowgroupboxgap.png"
gap_end_file="images/shadowgroupboxgap.png"}
image{
function=SHADOW_GAP
shadow=OUT
file="images/shadowgroupbox.png"
border={1,1,0,1}
stretch=TRUE
gap_start_file="images/shadowgroupboxgap.png"
gap_end_file="images/shadowgroupboxgap.png"}
image{
function=SHADOW_GAP
shadow=ETCHED_OUT
file="images/shadowgroupbox.png"
border={1,1,0,1}
stretch=TRUE
gap_start_file="images/shadowgroupboxgap.png"
gap_end_file="images/shadowgroupboxgap.png"}
image{
function=SHADOW_GAP
shadow=NONE
file="images/none.xpm"
stretch=FALSE
gap_start_file="images/none.xpm"
gap_end_file="images/none.xpm"}}}
class"GtkFrame"style"groupbox"

widget_class"*.<GtkFrame>*<GtkImage>"style"mistrender"
widget_class"*.<GtkFrame>*<GtkLabel>"style"mistrender"
