style"menu"{
bg[NORMAL]=shade(0.85,@bg_color)}
widget"*GtkWindow.gtk-combobox-popup-menu*"style"menu"
widget"*GtkMenu"style"menu"
widget_class"*<GtkMenu>*"style"menu"

style"menuitem"{
GtkMenuItem::toggle-spacing=5
ythickness=3
bg[PRELIGHT]=shade(0.75,@bg_color)
bg[SELECTED]=shade(0.75,@bg_color)
bg[ACTIVE]=shade(0.75,@bg_color)
fg[PRELIGHT]=@fg_color
fg[SELECTED]=@fg_color
fg[ACTIVE]=@fg_color
text[PRELIGHT]=@fg_color
text[SELECTED]=@fg_color
text[ACTIVE]=@fg_color
engine"pixmap"{
image{
function=BOX
state=PRELIGHT
file="images/menuitemprelight.xpm"
border={4,4,0,2}
stretch=TRUE
overlay_file="images/menuitemprelight.png"
overlay_border={4,4,0,2}
overlay_stretch=TRUE}}}
widget_class"*.<GtkMenu>.<GtkMenuItem>"style"menuitem"
widget"*GtkWindow.gtk-combobox-popup-menu"style"menuitem"

style"menuitem2"{
fg[PRELIGHT]=@fg_color
fg[SELECTED]=@fg_color
fg[ACTIVE]=@fg_color
text[PRELIGHT]=@fg_color
text[SELECTED]=@fg_color
text[ACTIVE]=@fg_color}
widget_class"*.<GtkMenu>.<GtkMenuItem>.<GtkLabel>"style"menuitem2"
widget"*GtkWindow.gtk-combobox-popup-menu*"style"menuitem2"

style"menuseperator"{
xthickness=0
ythickness=1
GtkSeparatorMenuItem::horizontal-padding=0
GtkMenuItem::toggle-spacing=0
GtkWidget::wide-separators=1
GtkMenuItem::separator-height=1
GtkMenu::shadow-type=GTK_SHADOW_NONE
engine"pixmap"{
image{
function=BOX
file="images/line.png"
border={1,0,0,0}
stretch=TRUE}}}
widget_class"*<GtkSeparatorMenuItem>*"style"menuseperator"

widget_class"*.<GtkMenuItem>*<GtkLabel>"style"mistrender"
