style"scale_pixmap"{
xthickness=1
ythickness=1
GtkScale::slider-length=18
GtkScale::value-spacing=1
GtkRange::trough-border=1
GtkRange::stepper-size=14
GtkRange::activate-slider=0
engine"pixmap"{
image{
function=BOX
detail="trough"
orientation=HORIZONTAL
file="images/scalehtrough.png"
border={5,4,6,6}
stretch=TRUE}
image{
function=SLIDER
orientation=HORIZONTAL
file="images/scalehslider.xpm"
border={1,1,4,4}
stretch=TRUE}
image{
function=BOX
detail="trough"
orientation=VERTICAL
file="images/scalevtrough.png"
border={6,6,4,4}
stretch=TRUE}
image{
function=SLIDER
orientation=VERTICAL
file="images/scalevslider.xpm"
border={4,6,1,1}
stretch=TRUE}}}
class"GtkScale"style"scale_pixmap"
