style"gtkspinbutton"{
xthickness=4
ythickness=2
GtkWidget::interior_focus=1
GtkWidget::internal-padding=0
engine"pixmap"{
image{
function=ARROW}
image{
function=BOX
state=NORMAL
detail="spinbutton_up"
file="images/spinup.png"
stretch=TRUE
border={1,1,1,1}
overlay_file="images/plus.png"
overlay_stretch=FALSE}
image{
function=BOX
state=NORMAL
detail="spinbutton_down"
file="images/spindown.png"
stretch=TRUE
border={1,1,1,1}
overlay_file="images/minus.png"
overlay_stretch=FALSE}
image{
function=BOX
state=PRELIGHT
detail="spinbutton_up"
file="images/spin313131.png"
stretch=TRUE
border={1,1,1,1}
overlay_file="images/plus.png"
overlay_stretch=FALSE}
image{
function=BOX
state=PRELIGHT
detail="spinbutton_down"
file="images/spin313131.png"
stretch=TRUE
border={1,1,1,1}
overlay_file="images/minus.png"
overlay_stretch=FALSE}
image{
function=BOX
state=ACTIVE
detail="spinbutton_up"
file="images/spin313131.png"
stretch=TRUE
border={1,1,1,1}
overlay_file="images/plus.png"
overlay_stretch=FALSE}
image{
function=BOX
state=ACTIVE
detail="spinbutton_down"
file="images/spin313131.png"
stretch=TRUE
border={1,1,1,1}
overlay_file="images/minus.png"
overlay_stretch=FALSE}
image{
function=BOX
state=SELECTED
detail="spinbutton_up"
file="images/spin313131.png"
stretch=TRUE
border={1,1,1,1}
overlay_file="images/plus.png"
overlay_stretch=FALSE}
image{
function=BOX
state=SELECTED
detail="spinbutton_down"
file="images/spin313131.png"
stretch=TRUE
border={1,1,1,1}
overlay_file="images/minus.png"
overlay_stretch=FALSE}
image{
function=BOX
state=INSENSITIVE
detail="spinbutton_up"
file="images/spinup.png"
stretch=TRUE
border={1,1,1,1}
overlay_file="images/plusdisabled.png"
overlay_stretch=FALSE}
image{
function=BOX
state=INSENSITIVE
detail="spinbutton_down"
file="images/spindown.png"
stretch=TRUE
border={1,1,1,1}
overlay_file="images/minusdisabled.png"
overlay_stretch=FALSE}}}
widget_class"*GtkSpinButton"style"gtkspinbutton"
