style"tooltip"{
xthickness=5
ythickness=5
fg[NORMAL]=@fg_color
fg[PRELIGHT]=@fg_color
fg[SELECTED]=@fg_color
fg[ACTIVE]=@fg_color
fg[INSENSITIVE]=@fg_color
bg[NORMAL]=@bg_color
bg[PRELIGHT]=@bg_color
bg[SELECTED]="#000000"
bg[ACTIVE]=@bg_color
bg[INSENSITIVE]=@bg_color
text[NORMAL]=@fg_color
text[PRELIGHT]=@fg_color
text[ACTIVE]=@fg_color
text[SELECTED]=@fg_color
text[INSENSITIVE]=@fg_color
base[NORMAL]=@bg_color
base[PRELIGHT]=@bg_color
base[SELECTED]=@bg_color
base[ACTIVE]=@bg_color
base[INSENSITIVE]=@bg_color
engine"mist"{}}
widget"gtk-tooltip*"style"tooltip"
widget_class"*GtkTooltip"style"tooltip"
