style"toolbarall"{
xthickness=0
ythickness=1
GtkToolbar::internal-padding=2
GtkToolbar::shadow-type=GTK_SHADOW_NONE
GtkToolbar::space-style=GTK_TOOLBAR_SPACE_LINE
GtkToolbar::button-relief=GTK_RELIEF_NONE
GtkToolbar::space-style=GTK_TOOLBAR_SPACE_EMPTY
GtkToolbar::space-size=5}
widget_class"*<GtkToolbar>"style"toolbarall"

style"toolbar"{
xthickness=0
ythickness=1
GtkToolbar::internal-padding=2
GtkToolbar::shadow-type=GTK_SHADOW_NONE
GtkToolbar::space-style=GTK_TOOLBAR_SPACE_LINE
GtkToolbar::button-relief=GTK_RELIEF_NONE
GtkToolbar::space-style=GTK_TOOLBAR_SPACE_EMPTY
GtkToolbar::space-size=5
bg[NORMAL]=shade(0.9,@bg_color)
bg[PRELIGHT]=shade(0.9,@bg_color)
bg[SELECTED]=shade(0.9,@bg_color)
bg[ACTIVE]=shade(0.9,@bg_color)
bg[INSENSITIVE]=shade(0.9,@bg_color)
engine"pixmap"{
image{
function=SHADOW
shadow=NONE
orientation=HORIZONTAL
file="images/shadowbottom.xpm"
border={0,0,0,1}
stretch=TRUE}}}
widget_class".<GtkWindow>.<GtkVBox>.<GtkToolbar>"style"toolbar"
widget_class".<GtkWindow>.<GtkTable>.<GtkToolbar>"style"toolbar"

style"dialogtoolbar"{
xthickness=0
ythickness=0
bg[NORMAL]=@bg_color
bg[PRELIGHT]=@bg_color
bg[SELECTED]=@bg_color
bg[ACTIVE]=@bg_color
bg[INSENSITIVE]=@bg_color
GtkToolbar::shadow-type=GTK_SHADOW_NONE
engine"pixmap"{
image{
function=SHADOW
shadow=NONE
orientation=HORIZONTAL
file="images/none.xpm"
stretch=FALSE}}}

widget_class"*.<GtkToolbar>*<GtkImage>"style"mistrender"
widget_class"*.<GtkToolbar>*<GtkLabel>"style"mistrender"
