[theme]
background = "black"
primary = "light white"
secondary = "light black"
title = "yellow"
playing = "yellow"
playing_selected = "black"
playing_bg = "black"
highlight = "black"
highlight_bg = "yellow"
error = "light white"
error_bg = "red"
statusbar = "black"
statusbar_progress = "yellow"
statusbar_bg = "yellow"
cmdline = "white"
cmdline_bg = "black"
