{
  config,
  pkgs,
  ...
}:
{
  config = {
    environment.systemPackages = with pkgs; [
      acpi
      gcc
      file
      epson-escpr2
      git
      gnumake
      gtk3
      gtk4
      gtk-engine-murrine
      htop
      vim
      unzip
      wget
      wireguard-tools
      ydotool
      xwayland-satellite
      wl-clipboard
      zip
    ];
    home-manager.users.${config.eyenx.user.name}.home.packages = with pkgs; [
      age
      awscli2
      alacritty
      bat
      bc
      brightnessctl
      buildah
      chart-testing
      chromium
      cilium-cli
      claude-code
      clipse
      comma
      cosign
      difftastic
      deadnix
      dig
      dive
      dunst
      dust
      fahrplan
      fd
      firefox
      fzf
      kanshi
      keyd
      kitty
      killall
      gcolor3
      geoipWithDatabase
      gammastep
      gimp
      gopass
      gomuks
      imv
      lsof
      lbdb
      libnotify
      libreoffice
      logseq
      mplayer
      nixd
      msmtp
      nix-index
      notmuch
      notmuch-mutt
      oama
      openssl
      ponymix
      pipes-rs
      restic
      ripgrep
      offlineimap
      slack
      ncpamixer
      neomutt
      neovim
      netbird
      networkmanagerapplet
      niri
      nodejs_24
      pavucontrol
      playerctl
      python3
      ruby
      swaybg
      swaylock
      tmux
      unstable.tmuxinator
      wayneko
      unstable.webdump
      wmenu
      windowtolayer
      zoxide
      zulip
    ];
  };
}
