{
  config,
  pkgs,
  ...
}:
{
  config = {
    environment.systemPackages = with pkgs; [
      acpi
      gcc
      file
      epson-escpr2
      git
      gnumake
      gtk3
      gtk4
      gtk-engine-murrine
      htop
      vim
      unzip
      wget
      wireguard-tools
      ydotool
      xwayland-satellite
      wl-clipboard
      zip
    ];
    home-manager.users.${config.eyenx.user.name}.home.packages = with pkgs; [
      age
      bc
      awscli2
      alacritty
      azure-cli
      bat
      bats
      brightnessctl
      buildah
      chart-testing
      chromium
      cilium-cli
      claude-code
      clipse
      cosign
      difftastic
      deadnix
      dig
      dive
      dunst
      dust
      dyff
      fahrplan
      fd
      firefox
      fluxcd
      fzf
      kanshi
      keyd
      kitty
      killall
      gcolor3
      geoipWithDatabase
      gammastep
      gimp
      gh
      gopass
      gomuks
      imv
      jq
      jwt-cli
      lazygit
      lsof
      lbdb
      libnotify
      libreoffice
      logseq
      mplayer
      nixd
      msmtp
      notmuch
      notmuch-mutt
      oama
      openshift
      opencode
      openssl
      ponymix
      pipes-rs
      restic
      ripgrep
      offlineimap
      slack
      ncpamixer
      neomutt
      neovim
      networkmanagerapplet
      niri
      nodejs_24
      pavucontrol
      playerctl
      podman
      podman-compose
      python3
      ruby
      openbao
      opentofu
      swaybg
      swaylock
      shell-gpt
      tmux
      unstable.tmuxinator
      wayneko
      wmenu
      windowtolayer
      yq-go
      zoxide
      zulip
    ];
  };
}
